### ISSUE TITLE
SingleM pipe fails for one sample only (“Not all read names found in metapackage sqlite3 database”)

### ISSUE THREAD

**Issue by MCeciC** [wwood/singlem#269]
Hi everyone,
I ran singlem pipe in a loop for multiple paired-end samples (about ~30 samples). The pipeline completed successfully for all samples except one (S28). For sample S28, SingleM crashed at the taxonomy-conversion step with this error:

_Converting DIAMOND IDs to taxons
Exception: Not all read names found in metapackage sqlite3 database_

I do get a complete S28_otu_table.tsv, but SingleM fails before (-p) producing the profile (.profile.tsv) and the Krona file.

All samples were run with the same command, same conda environment, and same metapackage. I also deleted the working directory and re-ran S28 from scratch, but the error persists only for this one sample.

Do you have any suggestions on what I can try or check to solve this?  
Thanks!

**Comment by wwood** [comment]
Hmm, what version is this? Possibly fixed in most recent?

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
From: MCeciC ***@***.***>
Sent: Thursday, December 4, 2025 8:46:14 AM
To: wwood/singlem ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [wwood/singlem] SingleM pipe fails for one sample only (“Not all read names found in metapackage sqlite3 database”) (Issue #269)

[https://avatars.githubusercontent.com/u/163445818?s=20&v=4]MCeciC created an issue (wwood/singlem#269)<https://github.com/wwood/singlem/issues/269>

Hi everyone,
I ran singlem pipe in a loop for multiple paired-end samples (about ~30 samples). The pipeline completed successfully for all samples except one (S28). For sample S28, SingleM crashed at the taxonomy-conversion step with this error:

Converting DIAMOND IDs to taxons
Exception: Not all read names found in metapackage sqlite3 database

I do get a complete S28_otu_table.tsv, but SingleM fails before (-p) producing the profile (.profile.tsv) and the Krona file.

All samples were run with the same command, same conda environment, and same metapackage. I also deleted the working directory and re-ran S28 from scratch, but the error persists only for this one sample.

Do you have any suggestions on what I can try or check to solve this?
Thanks!

―

**Comment by MCeciC** [comment]
Thanks for the quick response. 

I’ve now tested SingleM v0.20.3 together with the S5.4.0 GTDB_r220 metapackage.
Singlem pipe still fails during condense with:

_Found 11462 read names in metapackage sqlite3 database, expected 11490._  

Happy to provide the OTU table or debug outputs if that helps. Thanks again!

**Comment by wwood** [comment]
Any chance of passing the raw reads? I think this bug might need it. Just that sample.

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________

**Comment by MCeciC** [comment]
Here is the SRA entry for this sample:

BioProject: PRJNA1254264
BioSample (S28): SAMN51280524
SRR35421126 [https://trace.ncbi.nlm.nih.gov/Traces?run=SRR35421126]
SRA Submission: SRP580569 https://www.ncbi.nlm.nih.gov/biosample/SAMN51280524 

hope this helps. thank you!

**Comment by wwood** [comment]
yep, that should do it - I'll try to reproduce/fix. Thanks.

**Comment by MCeciC** [comment]
Hi Ben, just checking in — were you able to take a look at the bug?
Thanks!

**Comment by wwood** [comment]
I've started on it, and able to reproduce, which is nice. Less nice is how subtle it is - taking a lot of time to find the root cause.

**Comment by wwood** [comment]
Fixed in the main branch. Painful indeed, but we got there. Will be released in the next version (after 0.20.3).
